// ============================================================
//  WORDPATH — QUIZ DATA
// ============================================================
//  Hər söz üçün format:
//    { en: 'İngiliscə söz', tr: 'Düzgün Azərbaycanca tərcümə', wrong: 'Yanlış tərcümə' }
//
//  Hər səviyyə içində 10 quiz var.
//  Hər quizdə tam olaraq 20 söz olmalıdır.
//  Boş qalan quizlər oyunda "Tezliklə..." kimi görünür.
// ============================================================

const LEVELS = [

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 1 — A1: Başlanğıc                        ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'a1',
    name: 'A1 — Başlanğıc',
    icon: '🌱',
    color: '#4A8FE7',
    quizzes: [

     // ─────────────────────── QUIZ 1 — Peşələr ───────────────────────
[
  { en: 'actor',      tr: 'aktyor',        wrong: 'rejissor'   },
  { en: 'actress',    tr: 'aktrisa',       wrong: 'rəqqasə'    },
  { en: 'adult',      tr: 'böyük adam',    wrong: 'uşaq'       },
  { en: 'artist',     tr: 'rəssam',        wrong: 'musiqiçi'   },
  { en: 'dancer',     tr: 'rəqqas',        wrong: 'müğənni'    },
  { en: 'doctor',     tr: 'həkim',         wrong: 'müəllim'    },
  { en: 'driver',     tr: 'sürücü',        wrong: 'pilot'      },
  { en: 'farmer',     tr: 'fermer',        wrong: 'balıqçı'    },
  { en: 'nurse',      tr: 'tibb bacısı',   wrong: 'həkim'      },
  { en: 'player',     tr: 'oyunçu',        wrong: 'məşqçi'     },
  { en: 'policeman',  tr: 'polis',         wrong: 'gözətçi'    },
  { en: 'scientist',  tr: 'alim',          wrong: 'mühəndis'   },
  { en: 'singer',     tr: 'müğənni',       wrong: 'rəqqas'     },
  { en: 'student',    tr: 'tələbə',        wrong: 'müəllim'    },
  { en: 'teacher',    tr: 'müəllim',       wrong: 'direktor'   },
  { en: 'tourist',    tr: 'turist',        wrong: 'səfir'      },
  { en: 'visitor',    tr: 'ziyarətçi',     wrong: 'sakin'      },
  { en: 'waiter',     tr: 'ofisiant',      wrong: 'aşpaz'      },
  { en: 'worker',     tr: 'işçi',          wrong: 'müdir'      },
  { en: 'writer',     tr: 'yazıçı',        wrong: 'jurnalist'  },
],

// ─────────────────────── QUIZ 2 — Ümumi insanlar ───────────────────────
[
  { en: 'baby',       tr: 'körpə',         wrong: 'uşaq'       },
  { en: 'boy',        tr: 'oğlan',         wrong: 'qız'        },
  { en: 'child',      tr: 'uşaq',          wrong: 'gənc'       },
  { en: 'customer',   tr: 'müştəri',       wrong: 'satıcı'     },
  { en: 'girl',       tr: 'qız',           wrong: 'oğlan'      },
  { en: 'man',        tr: 'kişi',          wrong: 'qadın'      },
  { en: 'member',     tr: 'üzv',           wrong: 'rəhbər'     },
  { en: 'neighbour',  tr: 'qonşu',         wrong: 'dost'       },
  { en: 'partner',    tr: 'ortaq',         wrong: 'rəqib'      },
  { en: 'person',     tr: 'insan',         wrong: 'heyvan'     },
  { en: 'teenager',   tr: 'yeniyetmə',     wrong: 'körpə'      },
  { en: 'woman',      tr: 'qadın',         wrong: 'kişi'       },
  { en: 'people',     tr: 'insanlar',      wrong: 'heyvanlar'  },
  { en: 'friend',     tr: 'dost',          wrong: 'qonşu'      },
  { en: 'somebody',   tr: 'kimsə',         wrong: 'heç kim'    },
  { en: 'someone',    tr: 'biri',          wrong: 'hamı'       },
  { en: 'anybody',    tr: 'hər hansı biri',wrong: 'heç kim'    },
  { en: 'anyone',     tr: 'hər kəs',       wrong: 'heç biri'   },
  { en: 'nobody',     tr: 'heç kim',       wrong: 'hamı'       },
  { en: 'no one',     tr: 'heç kəs',       wrong: 'kimsə'      },
],

// ─────────────────────── QUIZ 3 — Ailə ───────────────────────
[
  { en: 'aunt',        tr: 'xala',         wrong: 'nənə'       },
  { en: 'boyfriend',   tr: 'oğlan dostu',  wrong: 'qardaş'     },
  { en: 'brother',     tr: 'qardaş',       wrong: 'bacı'       },
  { en: 'cousin',      tr: 'əmioğlu',      wrong: 'qardaş'     },
  { en: 'dad',         tr: 'ata',          wrong: 'baba'       },
  { en: 'daughter',    tr: 'qız övlad',    wrong: 'oğul'       },
  { en: 'family',      tr: 'ailə',         wrong: 'qrup'       },
  { en: 'father',      tr: 'ata',          wrong: 'ana'        },
  { en: 'girlfriend',  tr: 'qız dostu',    wrong: 'bacı'       },
  { en: 'grandfather', tr: 'baba',         wrong: 'əmi'        },
  { en: 'grandmother', tr: 'nənə',         wrong: 'xala'       },
  { en: 'grandparent', tr: 'nəsil böyüyü', wrong: 'valideyn'   },
  { en: 'husband',     tr: 'ər',           wrong: 'arvad'      },
  { en: 'mother',      tr: 'ana',          wrong: 'ata'        },
  { en: 'mum',         tr: 'mama',         wrong: 'baba'       },
  { en: 'parent',      tr: 'valideyn',     wrong: 'müəllim'    },
  { en: 'sister',      tr: 'bacı',         wrong: 'qardaş'     },
  { en: 'son',         tr: 'oğul',         wrong: 'qız övlad'  },
  { en: 'uncle',       tr: 'əmi',          wrong: 'baba'       },
  { en: 'wife',        tr: 'arvad',        wrong: 'ər'         },
],

// ─────────────────────── QUIZ 4 — Bədən ───────────────────────
[
  { en: 'arm',       tr: 'qol',          wrong: 'ayaq'       },
  { en: 'body',      tr: 'bədən',        wrong: 'üz'         },
  { en: 'ear',       tr: 'qulaq',        wrong: 'göz'        },
  { en: 'eye',       tr: 'göz',          wrong: 'qulaq'      },
  { en: 'face',      tr: 'üz',           wrong: 'baş'        },
  { en: 'foot',      tr: 'pəncə',        wrong: 'əl'         },
  { en: 'hair',      tr: 'saç',          wrong: 'qaş'        },
  { en: 'hand',      tr: 'əl',           wrong: 'qol'        },
  { en: 'head',      tr: 'baş',          wrong: 'boyun'      },
  { en: 'leg',       tr: 'ayaq',         wrong: 'qol'        },
  { en: 'mouth',     tr: 'ağız',         wrong: 'burun'      },
  { en: 'nose',      tr: 'burun',        wrong: 'ağız'       },
  { en: 'tooth',     tr: 'diş',          wrong: 'dil'        },
  { en: 'back',      tr: 'kürək',        wrong: 'qarın'      },
  { en: 'bottom',    tr: 'oturacaq',     wrong: 'üst'        },
  { en: 'skin',      tr: 'dəri',         wrong: 'sümük'      },
  { en: 'health',    tr: 'sağlamlıq',    wrong: 'xəstəlik'   },
  { en: 'diet',      tr: 'pəhriz',       wrong: 'idman'      },
  { en: 'exercise',  tr: 'məşq',         wrong: 'istirahət'  },
  { en: 'born',      tr: 'doğulmuş',     wrong: 'ölmüş'      },
],
      
{ type: 'exam', name: 'Exam 1 — Peşələr & İnsanlar', sourceQuizzes: [0,1,2,3] },

      // ─────────────────────── QUIZ 5 — Hisslər ───────────────────────
[
  { en: 'afraid',       tr: 'qorxmuş',          wrong: 'xoşbəxt'       },
  { en: 'angry',        tr: 'əsəbi',             wrong: 'sakit'         },
  { en: 'bored',        tr: 'darıxmış',          wrong: 'həyəcanlı'     },
  { en: 'excited',      tr: 'həyəcanlı',         wrong: 'yorğun'        },
  { en: 'happy',        tr: 'xoşbəxt',           wrong: 'kədərli'       },
  { en: 'hungry',       tr: 'ac',                wrong: 'susamış'       },
  { en: 'interested',   tr: 'maraqlanmış',       wrong: 'biganə'        },
  { en: 'sad',          tr: 'kədərli',           wrong: 'xoşbəxt'       },
  { en: 'sick',         tr: 'xəstə',             wrong: 'sağlam'        },
  { en: 'sorry',        tr: 'peşman',            wrong: 'razı'          },
  { en: 'thirsty',      tr: 'susamış',           wrong: 'ac'            },
  { en: 'tired',        tr: 'yorğun',            wrong: 'enerjili'      },
  { en: 'boring',       tr: 'cansıxıcı',         wrong: 'maraqlı'       },
  { en: 'exciting',     tr: 'həyəcanlandırıcı',  wrong: 'darıxdırıcı'   },
  { en: 'interesting',  tr: 'maraqlı',           wrong: 'sıxıcı'        },
  { en: 'dear',         tr: 'əziz',              wrong: 'uzaq'          },
  { en: 'to feel',      tr: 'hiss etmək',        wrong: 'görmək'        },
  { en: 'to hate',      tr: 'nifrət etmək',      wrong: 'sevmək'        },
  { en: 'to love',      tr: 'sevmək',            wrong: 'nifrət etmək'  },
  { en: 'to like',      tr: 'xoşlamaq',          wrong: 'sevməmək'      },
],

// ─────────────────────── QUIZ 6 — Müsbət Sifətlər ───────────────────────
[
  { en: 'amazing',     tr: 'heyrətamiz',         wrong: 'darıxdırıcı'   },
  { en: 'beautiful',   tr: 'gözəl',              wrong: 'çirkin'        },
  { en: 'cool',        tr: 'möhtəşəm',           wrong: 'sıradan'       },
  { en: 'delicious',   tr: 'dadlı',              wrong: 'dadsız'        },
  { en: 'fantastic',   tr: 'fantastik',          wrong: 'adi'           },
  { en: 'favourite',   tr: 'sevimli',            wrong: 'sevilməyən'    },
  { en: 'friendly',    tr: 'mehriban',           wrong: 'düşmənçilik'   },
  { en: 'funny',       tr: 'gülməli',            wrong: 'kədərli'       },
  { en: 'good',        tr: 'yaxşı',              wrong: 'pis'           },
  { en: 'great',       tr: 'əla',                wrong: 'zəif'          },
  { en: 'healthy',     tr: 'sağlam',             wrong: 'xəstə'         },
  { en: 'kind',        tr: 'xeyirxah',           wrong: 'zalım'         },
  { en: 'nice',        tr: 'xoş',                wrong: 'pis'           },
  { en: 'perfect',     tr: 'mükəmməl',           wrong: 'qüsurlu'       },
  { en: 'popular',     tr: 'məşhur',             wrong: 'naməlum'       },
  { en: 'pretty',      tr: 'cəlbedici',          wrong: 'çirkin'        },
  { en: 'special',     tr: 'xüsusi',             wrong: 'adi'           },
  { en: 'strong',      tr: 'güclü',              wrong: 'zəif'          },
  { en: 'wonderful',   tr: 'möhtəşəm',           wrong: 'dəhşətli'      },
  { en: 'modern',      tr: 'müasir',             wrong: 'köhnə'         },
],

// ─────────────────────── QUIZ 7 — Ölçü / Size & Shape ───────────────────────
[
  { en: 'big',         tr: 'böyük',              wrong: 'kiçik'         },
  { en: 'small',       tr: 'kiçik',              wrong: 'böyük'         },
  { en: 'large',       tr: 'iri',                wrong: 'dar'           },
  { en: 'little',      tr: 'balaca',             wrong: 'nəhəng'        },
  { en: 'long',        tr: 'uzun',               wrong: 'qısa'          },
  { en: 'short',       tr: 'qısa',               wrong: 'uzun'          },
  { en: 'tall',        tr: 'hündür',             wrong: 'alçaq'         },
  { en: 'high',        tr: 'yüksək',             wrong: 'aşağı'         },
  { en: 'fat',         tr: 'kök',                wrong: 'arıq'          },
  { en: 'full',        tr: 'dolu',               wrong: 'boş'           },
  { en: 'half',        tr: 'yarım',              wrong: 'tam'           },
  { en: 'top',         tr: 'üst',                wrong: 'alt'           },
  { en: 'bottom',      tr: 'alt',                wrong: 'üst'           },
  { en: 'middle',      tr: 'orta',               wrong: 'kənar'         },
  { en: 'front',       tr: 'ön',                 wrong: 'arxa'          },
  { en: 'back',        tr: 'arxa',               wrong: 'ön'            },
  { en: 'left',        tr: 'sol',                wrong: 'sağ'           },
  { en: 'right',       tr: 'sağ',                wrong: 'sol'           },
  { en: 'centre',      tr: 'mərkəz',             wrong: 'kənar'         },
  { en: 'side',        tr: 'yan',                wrong: 'orta'          },
],

// ─────────────────────── QUIZ 8 — Hal Sifətləri 1 ───────────────────────
[
  { en: 'bad',         tr: 'pis',                wrong: 'yaxşı'         },
  { en: 'busy',        tr: 'məşğul',             wrong: 'boş'           },
  { en: 'cheap',       tr: 'ucuz',               wrong: 'bahalı'        },
  { en: 'clean',       tr: 'təmiz',              wrong: 'çirkli'        },
  { en: 'cold',        tr: 'soyuq',              wrong: 'isti'          },
  { en: 'correct',     tr: 'düzgün',             wrong: 'səhv'          },
  { en: 'dangerous',   tr: 'təhlükəli',          wrong: 'təhlükəsiz'    },
  { en: 'dark',        tr: 'qaranlıq',           wrong: 'işıqlı'        },
  { en: 'different',   tr: 'fərqli',             wrong: 'eyni'          },
  { en: 'difficult',   tr: 'çətin',              wrong: 'asan'          },
  { en: 'dirty',       tr: 'çirkli',             wrong: 'təmiz'         },
  { en: 'dry',         tr: 'quru',               wrong: 'nəm'           },
  { en: 'early',       tr: 'erkən',              wrong: 'gec'           },
  { en: 'easy',        tr: 'asan',               wrong: 'çətin'         },
  { en: 'expensive',   tr: 'bahalı',             wrong: 'ucuz'          },
  { en: 'false',       tr: 'yalan',              wrong: 'həqiqi'        },
  { en: 'fast',        tr: 'sürətli',            wrong: 'yavaş'         },
  { en: 'fine',        tr: 'yaxşı',              wrong: 'pis'           },
  { en: 'free',        tr: 'azad',               wrong: 'məhkum'        },
  { en: 'hard',        tr: 'çətin',              wrong: 'asan'          },
],

// ─────────────────────── QUIZ 9 — Hal Sifətləri 2 ───────────────────────
[
  { en: 'hot',         tr: 'isti',               wrong: 'soyuq'         },
  { en: 'important',   tr: 'vacib',              wrong: 'əhəmiyyətsiz'  },
  { en: 'late',        tr: 'gec',                wrong: 'erkən'         },
  { en: 'married',     tr: 'evli',               wrong: 'subay'         },
  { en: 'old',         tr: 'köhnə',              wrong: 'yeni'          },
  { en: 'open',        tr: 'açıq',               wrong: 'bağlı'         },
  { en: 'opposite',    tr: 'əks',                wrong: 'eyni'          },
  { en: 'poor',        tr: 'kasıb',              wrong: 'varlı'         },
  { en: 'possible',    tr: 'mümkün',             wrong: 'qeyri-mümkün'  },
  { en: 'quick',       tr: 'tez',                wrong: 'yavaş'         },
  { en: 'quiet',       tr: 'sakit',              wrong: 'səs-küylü'     },
  { en: 'ready',       tr: 'hazır',              wrong: 'hazırsız'      },
  { en: 'real',        tr: 'həqiqi',             wrong: 'saxta'         },
  { en: 'rich',        tr: 'varlı',              wrong: 'kasıb'         },
  { en: 'same',        tr: 'eyni',               wrong: 'fərqli'        },
  { en: 'slow',        tr: 'yavaş',              wrong: 'sürətli'       },
  { en: 'sure',        tr: 'əmin',               wrong: 'şübhəli'       },
  { en: 'terrible',    tr: 'dəhşətli',           wrong: 'möhtəşəm'      },
  { en: 'true',        tr: 'doğru',              wrong: 'yalan'         },
  { en: 'warm',        tr: 'ilıq',               wrong: 'soyuq'         },
],
      { type: 'exam', name: 'Exam 2 — Hisslər & Sifətlər', sourceQuizzes: [4,5,6,7,8] },

// ─────────────────────── QUIZ 10 — Yemək / Food ───────────────────────
[
  { en: 'apple',       tr: 'alma',               wrong: 'armud'         },
  { en: 'banana',      tr: 'banan',              wrong: 'ərik'          },
  { en: 'carrot',      tr: 'yerkökü',            wrong: 'soğan'         },
  { en: 'fruit',       tr: 'meyvə',              wrong: 'tərəvəz'       },
  { en: 'onion',       tr: 'soğan',              wrong: 'sarımsaq'      },
  { en: 'orange',      tr: 'portağal',           wrong: 'limon'         },
  { en: 'pepper',      tr: 'bibər',              wrong: 'pomidor'       },
  { en: 'potato',      tr: 'kartof',             wrong: 'yerkökü'       },
  { en: 'tomato',      tr: 'pomidor',            wrong: 'bibər'         },
  { en: 'vegetable',   tr: 'tərəvəz',            wrong: 'meyvə'         },
  { en: 'salad',       tr: 'salat',              wrong: 'şorba'         },
  { en: 'plant',       tr: 'bitki',              wrong: 'heyvan'        },
  { en: 'lemon',       tr: 'limon',              wrong: 'portağal'      },
  { en: 'rice',        tr: 'düyü',               wrong: 'un'            },
  { en: 'bread',       tr: 'çörək',              wrong: 'kərə yağı'     },
  { en: 'butter',      tr: 'kərə yağı',          wrong: 'çörək'         },
  { en: 'flour',       tr: 'un',                 wrong: 'şəkər'         },
  { en: 'egg',         tr: 'yumurta',            wrong: 'süd'           },
  { en: 'sugar',       tr: 'şəkər',              wrong: 'duz'           },
  { en: 'salt',        tr: 'duz',                wrong: 'şəkər'         },
],
// ─────────────────────── QUIZ 11 — Yemək 2 / Ət & Dairy ───────────────────────
[
  { en: 'cake',        tr: 'tort',               wrong: 'çörək'         },
  { en: 'cheese',      tr: 'pendir',             wrong: 'kərə yağı'     },
  { en: 'chicken',     tr: 'toyuq',              wrong: 'balıq'         },
  { en: 'chocolate',   tr: 'şokolad',            wrong: 'karamel'       },
  { en: 'cream',       tr: 'qaymaq',             wrong: 'süd'           },
  { en: 'fish',        tr: 'balıq',              wrong: 'ət'            },
  { en: 'ice cream',   tr: 'dondurma',           wrong: 'tort'          },
  { en: 'meat',        tr: 'ət',                 wrong: 'toyuq'         },
  { en: 'milk',        tr: 'süd',                wrong: 'su'            },
  { en: 'pasta',       tr: 'makaron',            wrong: 'düyü'          },
  { en: 'pizza',       tr: 'pizza',              wrong: 'burger'        },
  { en: 'sandwich',    tr: 'sendviç',            wrong: 'pizza'         },
  { en: 'soup',        tr: 'şorba',              wrong: 'salat'         },
  { en: 'dish',        tr: 'yemək / qab',        wrong: 'içki'          },
  { en: 'food',        tr: 'qida / yemək',       wrong: 'içki'          },
  { en: 'snack',       tr: 'atıştırmalıq',       wrong: 'nahar'         },
  { en: 'butter',      tr: 'kərə yağı',          wrong: 'pendir'        },
  { en: 'diet',        tr: 'pəhriz',             wrong: 'resept'        },
  { en: 'cooking',     tr: 'bişirmə',            wrong: 'yemək yemə'    },
  { en: 'recipe',      tr: 'resept',             wrong: 'meny'          },
],

// ─────────────────────── QUIZ 12 — Yemək 3 / İçki & Meals ───────────────────────
[
  { en: 'beer',        tr: 'pivə',               wrong: 'şərab'         },
  { en: 'coffee',      tr: 'qəhvə',              wrong: 'çay'           },
  { en: 'juice',       tr: 'şirə / meyva suyu',  wrong: 'su'            },
  { en: 'milk',        tr: 'süd',                wrong: 'qəhvə'         },
  { en: 'tea',         tr: 'çay',                wrong: 'qəhvə'         },
  { en: 'water',       tr: 'su',                 wrong: 'şirə'          },
  { en: 'wine',        tr: 'şərab',              wrong: 'pivə'          },
  { en: 'breakfast',   tr: 'səhər yeməyi',       wrong: 'axşam yeməyi'  },
  { en: 'dinner',      tr: 'axşam yeməyi',       wrong: 'səhər yeməyi'  },
  { en: 'lunch',       tr: 'nahar',              wrong: 'səhər yeməyi'  },
  { en: 'meal',        tr: 'yemək / öyün',       wrong: 'içki'          },
  { en: 'menu',        tr: 'meny',               wrong: 'resept'        },
  { en: 'to drink',    tr: 'içmək',              wrong: 'yemək'         },
  { en: 'to eat',      tr: 'yemək',              wrong: 'içmək'         },
  { en: 'to cook',     tr: 'bişirmək',           wrong: 'sifariş etmək' },
  { en: 'to order',    tr: 'sifariş etmək',      wrong: 'dadmaq'        },
  { en: 'to taste',    tr: 'dadmaq',             wrong: 'bişirmək'      },
  { en: 'hungry',      tr: 'ac',                 wrong: 'susamış'       },
  { en: 'thirsty',     tr: 'susamış',            wrong: 'ac'            },
  { en: 'delicious',   tr: 'dadlı',              wrong: 'dadsız'        },
],
      { type: 'exam', name: 'Exam 3 — Yemək & İçki', sourceQuizzes: [10,11,12] },

// ─────────────────────── QUIZ 13 — Rənglər / Colours ───────────────────────
[
  { en: 'black',       tr: 'qara',               wrong: 'ağ'            },
  { en: 'blonde',      tr: 'sarışın',            wrong: 'qarayanız'     },
  { en: 'blue',        tr: 'mavi',               wrong: 'yaşıl'         },
  { en: 'brown',       tr: 'qəhvəyi',            wrong: 'boz'           },
  { en: 'green',       tr: 'yaşıl',              wrong: 'mavi'          },
  { en: 'grey',        tr: 'boz',                wrong: 'qəhvəyi'       },
  { en: 'orange',      tr: 'narıncı',            wrong: 'sarı'          },
  { en: 'pink',        tr: 'çəhrayı',            wrong: 'bənövşəyi'     },
  { en: 'purple',      tr: 'bənövşəyi',          wrong: 'çəhrayı'       },
  { en: 'red',         tr: 'qırmızı',            wrong: 'narıncı'       },
  { en: 'white',       tr: 'ağ',                 wrong: 'qara'          },
  { en: 'yellow',      tr: 'sarı',               wrong: 'narıncı'       },
  { en: 'colour',      tr: 'rəng',               wrong: 'çalar'         },
  { en: 'dark',        tr: 'tünd / qaranlıq',    wrong: 'açıq'          },
  { en: 'light',       tr: 'açıq / işıqlı',      wrong: 'tünd'          },
  { en: 'bright',      tr: 'parlaq',             wrong: 'solğun'        },
  { en: 'pale',        tr: 'solğun',             wrong: 'parlaq'        },
  { en: 'deep',        tr: 'dərin / tünd',       wrong: 'açıq'          },
  { en: 'shade',       tr: 'çalar / kölgə',      wrong: 'rəng'          },
],

// ─────────────────────── QUIZ 14 — Rəqəmlər 1 / Numbers 1–20 ───────────────────────
[
  { en: 'one',         tr: 'bir',                wrong: 'iki'           },
  { en: 'two',         tr: 'iki',                wrong: 'üç'            },
  { en: 'three',       tr: 'üç',                 wrong: 'dörd'          },
  { en: 'four',        tr: 'dörd',               wrong: 'beş'           },
  { en: 'five',        tr: 'beş',                wrong: 'altı'          },
  { en: 'six',         tr: 'altı',               wrong: 'yeddi'         },
  { en: 'seven',       tr: 'yeddi',              wrong: 'səkkiz'        },
  { en: 'eight',       tr: 'səkkiz',             wrong: 'doqquz'        },
  { en: 'nine',        tr: 'doqquz',             wrong: 'on'            },
  { en: 'ten',         tr: 'on',                 wrong: 'doqquz'        },
  { en: 'eleven',      tr: 'on bir',             wrong: 'on iki'        },
  { en: 'twelve',      tr: 'on iki',             wrong: 'on üç'         },
  { en: 'thirteen',    tr: 'on üç',              wrong: 'on dörd'       },
  { en: 'fourteen',    tr: 'on dörd',            wrong: 'on beş'        },
  { en: 'fifteen',     tr: 'on beş',             wrong: 'on altı'       },
  { en: 'sixteen',     tr: 'on altı',            wrong: 'on yeddi'      },
  { en: 'seventeen',   tr: 'on yeddi',           wrong: 'on səkkiz'     },
  { en: 'eighteen',    tr: 'on səkkiz',          wrong: 'on doqquz'     },
  { en: 'nineteen',    tr: 'on doqquz',          wrong: 'iyirmi'        },
  { en: 'twenty',      tr: 'iyirmi',             wrong: 'on doqquz'     },
],

// ─────────────────────── QUIZ 15 — Rəqəmlər 2 / Numbers 30–ordinals ───────────────────────
[
  { en: 'thirty',      tr: 'otuz',               wrong: 'qırx'          },
  { en: 'forty',       tr: 'qırx',               wrong: 'əlli'          },
  { en: 'fifty',       tr: 'əlli',               wrong: 'altmış'        },
  { en: 'sixty',       tr: 'altmış',             wrong: 'yetmiş'        },
  { en: 'seventy',     tr: 'yetmiş',             wrong: 'səksən'        },
  { en: 'eighty',      tr: 'səksən',             wrong: 'doxsan'        },
  { en: 'ninety',      tr: 'doxsan',             wrong: 'yüz'           },
  { en: 'hundred',     tr: 'yüz',                wrong: 'min'           },
  { en: 'thousand',    tr: 'min',                wrong: 'milyon'        },
  { en: 'million',     tr: 'milyon',             wrong: 'min'           },
  { en: 'first',       tr: 'birinci',            wrong: 'ikinci'        },
  { en: 'second',      tr: 'ikinci',             wrong: 'üçüncü'        },
  { en: 'third',       tr: 'üçüncü',             wrong: 'dördüncü'      },
  { en: 'fourth',      tr: 'dördüncü',           wrong: 'beşinci'       },
  { en: 'fifth',       tr: 'beşinci',            wrong: 'altıncı'       },
  { en: 'number',      tr: 'rəqəm / nömrə',      wrong: 'sıra'          },
  { en: 'half',        tr: 'yarım',              wrong: 'tam'           },
  { en: 'quarter',     tr: 'rüb / dörddə bir',   wrong: 'yarım'         },
  { en: 'once',        tr: 'bir dəfə',           wrong: 'iki dəfə'      },
  { en: 'twice',       tr: 'iki dəfə',           wrong: 'bir dəfə'      },
],
      { type: 'exam', name: 'Exam 4 — Rənglər & Rəqəmlər', sourceQuizzes: [14,15,16] },

// ─────────────────────── QUIZ 16 — Ev 1 / Rooms & Furniture ───────────────────────
[
  { en: 'apartment',   tr: 'mənzil',             wrong: 'ev'            },
  { en: 'bath',        tr: 'vanna',              wrong: 'duş'           },
  { en: 'bathroom',    tr: 'vanna otağı',        wrong: 'yataq otağı'   },
  { en: 'bed',         tr: 'çarpayı',            wrong: 'divan'         },
  { en: 'bedroom',     tr: 'yataq otağı',        wrong: 'qonaq otağı'   },
  { en: 'building',    tr: 'bina',               wrong: 'mənzil'        },
  { en: 'chair',       tr: 'stul',               wrong: 'masa'          },
  { en: 'clock',       tr: 'saat',               wrong: 'təqvim'        },
  { en: 'desk',        tr: 'iş masası',          wrong: 'stul'          },
  { en: 'door',        tr: 'qapı',               wrong: 'pəncərə'       },
  { en: 'flat',        tr: 'mənzil',             wrong: 'villa'         },
  { en: 'floor',       tr: 'döşəmə / mərtəbə',   wrong: 'tavan'         },
  { en: 'home',        tr: 'ev / yuva',          wrong: 'ofis'          },
  { en: 'house',       tr: 'ev',                 wrong: 'mənzil'        },
  { en: 'kitchen',     tr: 'mətbəx',             wrong: 'hamam'         },
  { en: 'room',        tr: 'otaq',               wrong: 'koridor'       },
  { en: 'sofa',        tr: 'divan',              wrong: 'stul'          },
  { en: 'table',       tr: 'masa',               wrong: 'stul'          },
  { en: 'toilet',      tr: 'tualet',             wrong: 'hamam'         },
  { en: 'wall',        tr: 'divar',              wrong: 'tavan'         },
],

// ─────────────────────── QUIZ 17 — Ev 2 / Household objects ───────────────────────
[
  { en: 'bag',         tr: 'çanta',              wrong: 'qutu'          },
  { en: 'bottle',      tr: 'şüşə / butulka',     wrong: 'stəkan'        },
  { en: 'box',         tr: 'qutu',               wrong: 'çanta'         },
  { en: 'cup',         tr: 'fincan',             wrong: 'stəkan'        },
  { en: 'garden',      tr: 'bağça',              wrong: 'həyət'         },
  { en: 'glass',       tr: 'stəkan / şüşə',      wrong: 'fincan'        },
  { en: 'key',         tr: 'açar',               wrong: 'qıfıl'         },
  { en: 'lamp',        tr: 'çıraq / lampa',       wrong: 'pəncərə'       },
  { en: 'machine',     tr: 'maşın / cihaz',       wrong: 'alət'          },
  { en: 'paper',       tr: 'kağız',              wrong: 'dəftər'        },
  { en: 'pen',         tr: 'qələm',              wrong: 'karandaş'      },
  { en: 'pencil',      tr: 'karandaş',           wrong: 'qələm'         },
  { en: 'picture',     tr: 'şəkil / rəsm',       wrong: 'poster'        },
  { en: 'plant',       tr: 'bitki',              wrong: 'çiçək'         },
  { en: 'shower',      tr: 'duş',                wrong: 'vanna'         },
  { en: 'window',      tr: 'pəncərə',            wrong: 'qapı'          },
  { en: 'upstairs',    tr: 'yuxarı mərtəbədə',   wrong: 'aşağı mərtəbədə' },
  { en: 'downstairs',  tr: 'aşağı mərtəbədə',    wrong: 'yuxarı mərtəbədə' },
  { en: 'inside',      tr: 'içəridə',            wrong: 'çöldə'         },
  { en: 'outside',     tr: 'çöldə',              wrong: 'içəridə'       },
],
// ─────────────────────── QUIZ 18 — Şəhər 1 / City buildings ───────────────────────
[
  { en: 'airport',      tr: 'hava limanı',        wrong: 'stansiya'       },
  { en: 'bank',         tr: 'bank',               wrong: 'ofis'           },
  { en: 'cafe',         tr: 'kafe',               wrong: 'restoran'       },
  { en: 'cinema',       tr: 'kinoteatr',          wrong: 'teatr'          },
  { en: 'city',         tr: 'şəhər',              wrong: 'kənd'           },
  { en: 'club',         tr: 'klub',               wrong: 'kafe'           },
  { en: 'college',      tr: 'kollec',             wrong: 'universitet'    },
  { en: 'gym',          tr: 'idman zalı',         wrong: 'hovuz'          },
  { en: 'hospital',     tr: 'xəstəxana',          wrong: 'aptek'          },
  { en: 'hotel',        tr: 'otel',               wrong: 'hostel'         },
  { en: 'library',      tr: 'kitabxana',          wrong: 'muzey'          },
  { en: 'market',       tr: 'bazar',              wrong: 'supermarket'    },
  { en: 'museum',       tr: 'muzey',              wrong: 'kitabxana'      },
  { en: 'office',       tr: 'ofis',               wrong: 'mağaza'         },
  { en: 'park',         tr: 'park',               wrong: 'bağça'          },
  { en: 'pool',         tr: 'hovuz',              wrong: 'idman zalı'     },
  { en: 'restaurant',   tr: 'restoran',           wrong: 'kafe'           },
  { en: 'school',       tr: 'məktəb',             wrong: 'kollec'         },
  { en: 'supermarket',  tr: 'supermarket',        wrong: 'bazar'          },
  { en: 'theatre',      tr: 'teatr',              wrong: 'kinoteatr'      },
],

// ─────────────────────── QUIZ 19 — Şəhər 2 / Places & areas ───────────────────────
[
  { en: 'area',         tr: 'ərazi / rayon',      wrong: 'ölkə'           },
  { en: 'bar',          tr: 'bar',                wrong: 'kafe'           },
  { en: 'capital',      tr: 'paytaxt',            wrong: 'şəhər'          },
  { en: 'centre',       tr: 'mərkəz',             wrong: 'kənar'          },
  { en: 'country',      tr: 'ölkə',               wrong: 'şəhər'          },
  { en: 'farm',         tr: 'ferma',              wrong: 'bağça'          },
  { en: 'place',        tr: 'yer / məkan',        wrong: 'ərazi'          },
  { en: 'police',       tr: 'polis',              wrong: 'ordu'           },
  { en: 'post',         tr: 'poçt',               wrong: 'bank'           },
  { en: 'station',      tr: 'stansiya / vağzal',  wrong: 'hava limanı'    },
  { en: 'street',       tr: 'küçə',               wrong: 'prospekt'       },
  { en: 'town',         tr: 'qəsəbə',             wrong: 'kənd'           },
  { en: 'university',   tr: 'universitet',        wrong: 'kollec'         },
  { en: 'village',      tr: 'kənd',               wrong: 'qəsəbə'         },
  { en: 'world',        tr: 'dünya',              wrong: 'ölkə'           },
  { en: 'address',      tr: 'ünvan',              wrong: 'poçt indeksi'   },
  { en: 'floor',        tr: 'mərtəbə / döşəmə',  wrong: 'tavan'          },
  { en: 'space',        tr: 'məkan / kosmoz',     wrong: 'yer'            },
  { en: 'top',          tr: 'üst / zirvə',        wrong: 'alt'            },
  { en: 'bottom',       tr: 'alt / dib',          wrong: 'üst'            },
],

// ─────────────────────── QUIZ 20 — Təbiət / Nature & Geography ───────────────────────
[
  { en: 'beach',        tr: 'çimərlik',           wrong: 'ada'            },
  { en: 'east',         tr: 'şərq',               wrong: 'qərb'           },
  { en: 'island',       tr: 'ada',                wrong: 'yarımada'       },
  { en: 'land',         tr: 'torpaq / ərazi',     wrong: 'dəniz'          },
  { en: 'mountain',     tr: 'dağ',                wrong: 'təpə'           },
  { en: 'north',        tr: 'şimal',              wrong: 'cənub'          },
  { en: 'river',        tr: 'çay',                wrong: 'göl'            },
  { en: 'road',         tr: 'yol',                wrong: 'küçə'           },
  { en: 'sea',          tr: 'dəniz',              wrong: 'okean'          },
  { en: 'south',        tr: 'cənub',              wrong: 'şimal'          },
  { en: 'west',         tr: 'qərb',               wrong: 'şərq'           },
  { en: 'air',          tr: 'hava',               wrong: 'külək'          },
  { en: 'fire',         tr: 'od / atəş',          wrong: 'su'             },
  { en: 'flower',       tr: 'çiçək',              wrong: 'ağac'           },
  { en: 'ice',          tr: 'buz',                wrong: 'qar'            },
  { en: 'light',        tr: 'işıq',               wrong: 'kölgə'          },
  { en: 'rain',         tr: 'yağış',              wrong: 'qar'            },
  { en: 'snow',         tr: 'qar',                wrong: 'yağış'          },
  { en: 'sun',          tr: 'günəş',              wrong: 'ay'             },
  { en: 'tree',         tr: 'ağac',               wrong: 'kol'            },
],
      { type: 'exam', name: 'Exam 5 — Şəhər & Təbiət', sourceQuizzes: [18,19,20,21] },

// ─────────────────────── QUIZ 21 — Heyvanlar / Animals ───────────────────────
[
  { en: 'animal',       tr: 'heyvan',             wrong: 'bitki'          },
  { en: 'bird',         tr: 'quş',                wrong: 'balıq'          },
  { en: 'cat',          tr: 'pişik',              wrong: 'it'             },
  { en: 'cow',          tr: 'inək',               wrong: 'keçi'           },
  { en: 'dog',          tr: 'it',                 wrong: 'pişik'          },
  { en: 'elephant',     tr: 'fil',                wrong: 'aslan'          },
  { en: 'fish',         tr: 'balıq',              wrong: 'quş'            },
  { en: 'horse',        tr: 'at',                 wrong: 'eşşək'          },
  { en: 'lion',         tr: 'aslan',              wrong: 'pələng'         },
  { en: 'mouse',        tr: 'siçan',              wrong: 'dovşan'         },
  { en: 'pig',          tr: 'donuz',              wrong: 'qoyun'          },
  { en: 'rabbit',       tr: 'dovşan',             wrong: 'siçan'          },
  { en: 'sheep',        tr: 'qoyun',              wrong: 'keçi'           },
  { en: 'snake',        tr: 'ilan',               wrong: 'kərtənkələ'     },
  { en: 'weather',      tr: 'hava / iqlim',       wrong: 'mənzərə'        },
  { en: 'water',        tr: 'su',                 wrong: 'hava'           },
  { en: 'rock',         tr: 'qaya / daş',         wrong: 'torpaq'         },
  { en: 'wood',         tr: 'taxta / meşə',       wrong: 'daş'            },
  { en: 'grass',        tr: 'ot / çəmən',         wrong: 'ağac'           },
  { en: 'farm',         tr: 'ferma',              wrong: 'bağça'          },
],

// ─────────────────────── QUIZ 22 — Nəqliyyat / Transport ───────────────────────
[
  { en: 'bicycle',      tr: 'velosiped',          wrong: 'motosiklet'     },
  { en: 'bike',         tr: 'velosiped / moto',   wrong: 'avtomobil'      },
  { en: 'boat',         tr: 'qayıq',              wrong: 'gəmi'           },
  { en: 'bus',          tr: 'avtobus',            wrong: 'trolleybus'     },
  { en: 'car',          tr: 'avtomobil',          wrong: 'avtobus'        },
  { en: 'flight',       tr: 'uçuş',               wrong: 'səyahət'        },
  { en: 'plane',        tr: 'təyyarə',            wrong: 'vertolyot'      },
  { en: 'taxi',         tr: 'taksi',              wrong: 'avtobus'        },
  { en: 'train',        tr: 'qatar',              wrong: 'metro'          },
  { en: 'driving',      tr: 'sürücülük',          wrong: 'uçuş'           },
  { en: 'traffic',      tr: 'nəqliyyat / tıxac',  wrong: 'yol'            },
  { en: 'trip',         tr: 'səfər / gəzinti',    wrong: 'yol'            },
  { en: 'journey',      tr: 'səyahət',            wrong: 'gəzinti'        },
  { en: 'travel',       tr: 'səyahət etmək',      wrong: 'uçmaq'          },
  { en: 'ticket',       tr: 'bilet',              wrong: 'pasport'        },
  { en: 'passport',     tr: 'pasport',            wrong: 'bilet'          },
  { en: 'to drive',     tr: 'sürmək',             wrong: 'uçmaq'          },
  { en: 'to fly',       tr: 'uçmaq',              wrong: 'sürmək'         },
  { en: 'to ride',      tr: 'minmək / sürmək',    wrong: 'gətirmək'       },
  { en: 'to travel',    tr: 'səyahət etmək',      wrong: 'köçmək'         },
],

// ─────────────────────── QUIZ 23 — Geyim / Clothes & Accessories ───────────────────────
[
  { en: 'boot',         tr: 'çəkmə',              wrong: 'ayaqqabı'       },
  { en: 'coat',         tr: 'palto',              wrong: 'gödəkçə'        },
  { en: 'dress',        tr: 'don',                wrong: 'ətək'           },
  { en: 'hat',          tr: 'papaq / şlyapa',     wrong: 'şal'            },
  { en: 'jacket',       tr: 'gödəkçə',            wrong: 'palto'          },
  { en: 'jeans',        tr: 'cins şalvar',        wrong: 'şalvar'         },
  { en: 'shirt',        tr: 'köynək',             wrong: 'pencək'         },
  { en: 'shoe',         tr: 'ayaqqabı',           wrong: 'çəkmə'          },
  { en: 'skirt',        tr: 'ətək',               wrong: 'don'            },
  { en: 'sweater',      tr: 'sviter',             wrong: 'köynək'         },
  { en: 'T-shirt',      tr: 'futbolka',           wrong: 'köynək'         },
  { en: 'trousers',     tr: 'şalvar',             wrong: 'cins şalvar'    },
  { en: 'umbrella',     tr: 'çətir',              wrong: 'papaq'          },
  { en: 'watch',        tr: 'saat',               wrong: 'üzük'           },
  { en: 'clothes',      tr: 'geyim / paltar',     wrong: 'aksesuar'       },
  { en: 'style',        tr: 'üslub / stil',       wrong: 'moda'           },
  { en: 'pair',         tr: 'cüt',                wrong: 'ədəd'           },
  { en: 'to wear',      tr: 'geymək',             wrong: 'çıxarmaq'       },
  { en: 'to dress',     tr: 'geyindirmək',        wrong: 'soyundırmaq'    },
  { en: 'fashion',      tr: 'moda',               wrong: 'stil'           },
],

// ─────────────────────── QUIZ 24 — Zaman 1 / Days & Months ───────────────────────
[
  { en: 'Monday',       tr: 'bazar ertəsi',       wrong: 'çərşənbə'       },
  { en: 'Tuesday',      tr: 'çərşənbə axşamı',    wrong: 'bazar ertəsi'   },
  { en: 'Wednesday',    tr: 'çərşənbə',           wrong: 'cümə axşamı'    },
  { en: 'Thursday',     tr: 'cümə axşamı',        wrong: 'çərşənbə'       },
  { en: 'Friday',       tr: 'cümə',               wrong: 'şənbə'          },
  { en: 'Saturday',     tr: 'şənbə',              wrong: 'bazar'          },
  { en: 'Sunday',       tr: 'bazar',              wrong: 'şənbə'          },
  { en: 'January',      tr: 'yanvar',             wrong: 'fevral'         },
  { en: 'February',     tr: 'fevral',             wrong: 'yanvar'         },
  { en: 'March',        tr: 'mart',               wrong: 'aprel'          },
  { en: 'April',        tr: 'aprel',              wrong: 'mart'           },
  { en: 'May',          tr: 'may',                wrong: 'iyun'           },
  { en: 'June',         tr: 'iyun',               wrong: 'may'            },
  { en: 'July',         tr: 'iyul',               wrong: 'avqust'         },
  { en: 'August',       tr: 'avqust',             wrong: 'iyul'           },
  { en: 'September',    tr: 'sentyabr',           wrong: 'oktyabr'        },
  { en: 'October',      tr: 'oktyabr',            wrong: 'sentyabr'       },
  { en: 'November',     tr: 'noyabr',             wrong: 'dekabr'         },
  { en: 'December',     tr: 'dekabr',             wrong: 'noyabr'         },
  { en: 'week',         tr: 'həftə',              wrong: 'ay'             },
],
      { type: 'exam', name: 'Exam 6 — Nəqliyyat & Geyim', sourceQuizzes: [22,23,24] },

// ─────────────────────── QUIZ 25 — Zaman 2 / General time ───────────────────────
[
  { en: 'afternoon',    tr: 'günorta sonrası',    wrong: 'səhər'          },
  { en: 'age',          tr: 'yaş / dövr',         wrong: 'müddət'         },
  { en: 'autumn',       tr: 'payız',              wrong: 'yaz'            },
  { en: 'date',         tr: 'tarix',              wrong: 'vaxt'           },
  { en: 'day',          tr: 'gün',                wrong: 'gecə'           },
  { en: 'evening',      tr: 'axşam',              wrong: 'gecə'           },
  { en: 'future',       tr: 'gələcək',            wrong: 'keçmiş'         },
  { en: 'holiday',      tr: 'tətil / bayram',     wrong: 'iş günü'        },
  { en: 'hour',         tr: 'saat',               wrong: 'dəqiqə'         },
  { en: 'midnight',     tr: 'gecə yarısı',        wrong: 'günorta'        },
  { en: 'minute',       tr: 'dəqiqə',             wrong: 'saniyə'         },
  { en: 'moment',       tr: 'an / məqam',         wrong: 'dövr'           },
  { en: 'month',        tr: 'ay',                 wrong: 'həftə'          },
  { en: 'morning',      tr: 'səhər',              wrong: 'axşam'          },
  { en: 'night',        tr: 'gecə',               wrong: 'gündüz'         },
  { en: 'noon',         tr: 'günorta',            wrong: 'gecə yarısı'    },
  { en: 'past',         tr: 'keçmiş',             wrong: 'gələcək'        },
  { en: 'period',       tr: 'dövr / müddət',      wrong: 'an'             },
  { en: 'spring',       tr: 'yaz',                wrong: 'payız'          },
  { en: 'summer',       tr: 'yay',                wrong: 'qış'            },
],
// ─────────────────────── QUIZ 26 — Zaman 3 / More time words ───────────────────────
[
  { en: 'time',         tr: 'vaxt / zaman',       wrong: 'dövr'           },
  { en: 'today',        tr: 'bu gün',             wrong: 'sabah'          },
  { en: 'tomorrow',     tr: 'sabah',              wrong: 'dünən'          },
  { en: 'tonight',      tr: 'bu gecə',            wrong: 'bu səhər'       },
  { en: 'weekend',      tr: 'həftə sonu',         wrong: 'iş günü'        },
  { en: 'winter',       tr: 'qış',                wrong: 'yay'            },
  { en: 'year',         tr: 'il',                 wrong: 'ay'             },
  { en: 'yesterday',    tr: 'dünən',              wrong: 'bu gün'         },
  { en: 'second',       tr: 'saniyə',             wrong: 'dəqiqə'         },
  { en: 'birthday',     tr: 'ad günü',            wrong: 'bayram'         },
  { en: 'festival',     tr: 'festival',           wrong: 'konsert'        },
  { en: 'ago',          tr: 'əvvəl / bundan önce', wrong: 'sonra'         },
  { en: 'now',          tr: 'indi',               wrong: 'sonra'          },
  { en: 'then',         tr: 'sonra / o zaman',    wrong: 'indi'           },
  { en: 'soon',         tr: 'tezliklə',           wrong: 'gec'            },
  { en: 'late',         tr: 'gec',                wrong: 'erkən'          },
  { en: 'early',        tr: 'erkən',              wrong: 'gec'            },
  { en: 'always',       tr: 'həmişə',             wrong: 'heç vaxt'       },
  { en: 'never',        tr: 'heç vaxt',           wrong: 'həmişə'         },
  { en: 'often',        tr: 'tez-tez',            wrong: 'nadir hallarda' },
],
      { type: 'exam', name: 'Exam 7 — Zaman', sourceQuizzes: [25,26,27] },

// ─────────────────────── QUIZ 27 — Pul / Money & Shopping ───────────────────────
[
  { en: 'bill',         tr: 'hesab / əskinaz',    wrong: 'kart'           },
  { en: 'card',         tr: 'kart',               wrong: 'əskinaz'        },
  { en: 'cent',         tr: 'sent',               wrong: 'dollar'         },
  { en: 'dollar',       tr: 'dollar',             wrong: 'euro'           },
  { en: 'euro',         tr: 'avro',               wrong: 'funt'           },
  { en: 'money',        tr: 'pul',                wrong: 'qiymət'         },
  { en: 'pound',        tr: 'funt',               wrong: 'avro'           },
  { en: 'price',        tr: 'qiymət',             wrong: 'endirim'        },
  { en: 'shop',         tr: 'mağaza',             wrong: 'bazar'          },
  { en: 'shopping',     tr: 'alış-veriş',         wrong: 'satış'          },
  { en: 'to buy',       tr: 'almaq',              wrong: 'satmaq'         },
  { en: 'to cost',      tr: 'başa gəlmək',        wrong: 'ödəmək'         },
  { en: 'to pay',       tr: 'ödəmək',             wrong: 'almaq'          },
  { en: 'to order',     tr: 'sifariş etmək',      wrong: 'ödəmək'         },
  { en: 'cheap',        tr: 'ucuz',               wrong: 'bahalı'         },
  { en: 'expensive',    tr: 'bahalı',             wrong: 'ucuz'           },
  { en: 'free',         tr: 'pulsuz',             wrong: 'bahalı'         },
  { en: 'rich',         tr: 'varlı',              wrong: 'kasıb'          },
  { en: 'poor',         tr: 'kasıb',              wrong: 'varlı'          },
  { en: 'market',       tr: 'bazar',              wrong: 'mağaza'         },
],

// ─────────────────────── QUIZ 28 — Texnologiya / Technology ───────────────────────
[
  { en: 'blog',         tr: 'bloq',               wrong: 'vebsayt'        },
  { en: 'camera',       tr: 'kamera',             wrong: 'foto'           },
  { en: 'CD',           tr: 'CD disk',            wrong: 'DVD'            },
  { en: 'computer',     tr: 'kompüter',           wrong: 'planşet'        },
  { en: 'DVD',          tr: 'DVD disk',           wrong: 'CD'             },
  { en: 'email',        tr: 'elektron poçt',      wrong: 'mesaj'          },
  { en: 'internet',     tr: 'internet',           wrong: 'şəbəkə'         },
  { en: 'message',      tr: 'mesaj',              wrong: 'email'          },
  { en: 'online',       tr: 'onlayn',             wrong: 'oflayn'         },
  { en: 'phone',        tr: 'telefon',            wrong: 'planşet'        },
  { en: 'photo',        tr: 'foto / şəkil',       wrong: 'video'          },
  { en: 'photograph',   tr: 'fotoşəkil',          wrong: 'şəkil çəkmək'  },
  { en: 'programme',    tr: 'proqram',            wrong: 'tətbiq'         },
  { en: 'telephone',    tr: 'telefon',            wrong: 'radio'          },
  { en: 'television',   tr: 'televiziya',         wrong: 'radio'          },
  { en: 'text',         tr: 'mətn / yazı',        wrong: 'mesaj'          },
  { en: 'TV',           tr: 'televizor',          wrong: 'radio'          },
  { en: 'video',        tr: 'video',              wrong: 'audio'          },
  { en: 'website',      tr: 'vebsayt',            wrong: 'bloq'           },
  { en: 'screen',       tr: 'ekran',              wrong: 'klaviatura'     },
],

// ─────────────────────── QUIZ 29 — Media / Media & Entertainment ───────────────────────
[
  { en: 'article',      tr: 'məqalə',             wrong: 'xəbər'          },
  { en: 'book',         tr: 'kitab',              wrong: 'jurnal'         },
  { en: 'film',         tr: 'film',               wrong: 'serial'         },
  { en: 'magazine',     tr: 'jurnal',             wrong: 'qəzet'          },
  { en: 'movie',        tr: 'film / kino',        wrong: 'serial'         },
  { en: 'music',        tr: 'musiqi',             wrong: 'mahnı'          },
  { en: 'newspaper',    tr: 'qəzet',              wrong: 'jurnal'         },
  { en: 'news',         tr: 'xəbər',              wrong: 'məqalə'         },
  { en: 'photo',        tr: 'şəkil / foto',       wrong: 'video'          },
  { en: 'pop',          tr: 'pop musiqi',         wrong: 'rok'            },
  { en: 'programme',    tr: 'proqram / verilişi', wrong: 'kanal'          },
  { en: 'radio',        tr: 'radio',              wrong: 'televiziya'     },
  { en: 'report',       tr: 'hesabat / xəbər',    wrong: 'məqalə'         },
  { en: 'rock',         tr: 'rok musiqi',         wrong: 'pop'            },
  { en: 'show',         tr: 'şou / verilişi',     wrong: 'konsert'        },
  { en: 'song',         tr: 'mahnı',              wrong: 'musiqi'         },
  { en: 'story',        tr: 'hekayə',             wrong: 'roman'          },
  { en: 'video',        tr: 'video',              wrong: 'audio'          },
  { en: 'band',         tr: 'qrup / ansambl',     wrong: 'orkestra'       },
  { en: 'concert',      tr: 'konsert',            wrong: 'şou'            },
],
      { type: 'exam', name: 'Exam 8 — Texnologiya & Media', sourceQuizzes: [28,29,30] },

// ─────────────────────── QUIZ 30 — Məktəb 1 / School & Study ───────────────────────
[
  { en: 'answer',       tr: 'cavab',              wrong: 'sual'           },
  { en: 'class',        tr: 'sinif / dərs',       wrong: 'kurs'           },
  { en: 'classroom',    tr: 'sinif otağı',        wrong: 'laboratoriya'   },
  { en: 'course',       tr: 'kurs',               wrong: 'dərs'           },
  { en: 'detail',       tr: 'detal / təfərrüat',  wrong: 'nümunə'         },
  { en: 'dialogue',     tr: 'dialoq',             wrong: 'monoloq'        },
  { en: 'dictionary',   tr: 'lüğət',              wrong: 'kitab'          },
  { en: 'exam',         tr: 'imtahan',            wrong: 'test'           },
  { en: 'example',      tr: 'nümunə / misal',     wrong: 'tapşırıq'       },
  { en: 'exercise',     tr: 'məşq / tapşırıq',    wrong: 'nümunə'         },
  { en: 'geography',    tr: 'coğrafiya',          wrong: 'tarix'          },
  { en: 'history',      tr: 'tarix',              wrong: 'coğrafiya'      },
  { en: 'homework',     tr: 'ev tapşırığı',       wrong: 'sinif işi'      },
  { en: 'language',     tr: 'dil',                wrong: 'ləhcə'          },
  { en: 'lesson',       tr: 'dərs',               wrong: 'kurs'           },
  { en: 'letter',       tr: 'hərf / məktub',      wrong: 'söz'            },
  { en: 'note',         tr: 'qeyd',               wrong: 'məqalə'         },
  { en: 'page',         tr: 'səhifə',             wrong: 'paraqraf'       },
  { en: 'paragraph',    tr: 'paraqraf',           wrong: 'cümlə'          },
  { en: 'phrase',       tr: 'ifadə / söz birləşməsi', wrong: 'cümlə'     },
],
// ─────────────────────── QUIZ 31 — Məktəb 2 / More school words ───────────────────────
[
  { en: 'practice',    tr: 'təcrübə / məşq',     wrong: 'nəzəriyyə'      },
  { en: 'question',    tr: 'sual',                wrong: 'cavab'          },
  { en: 'reading',     tr: 'oxuma',              wrong: 'yazma'          },
  { en: 'rule',        tr: 'qayda',              wrong: 'istisna'        },
  { en: 'science',     tr: 'elm',                wrong: 'tarix'          },
  { en: 'section',     tr: 'bölmə',              wrong: 'paraqraf'       },
  { en: 'sentence',    tr: 'cümlə',              wrong: 'söz'            },
  { en: 'spelling',    tr: 'orfoqrafiya / yazılış', wrong: 'tələffüz'    },
  { en: 'subject',     tr: 'fənn / mövzu',       wrong: 'dərs'           },
  { en: 'test',        tr: 'test',               wrong: 'imtahan'        },
  { en: 'title',       tr: 'başlıq',             wrong: 'mövzu'          },
  { en: 'word',        tr: 'söz',                wrong: 'hərf'           },
  { en: 'writing',     tr: 'yazma',              wrong: 'oxuma'          },
  { en: 'to learn',    tr: 'öyrənmək',           wrong: 'öyrətmək'       },
  { en: 'to read',     tr: 'oxumaq',             wrong: 'yazmaq'         },
  { en: 'to study',    tr: 'oxumaq / öyrənmək',  wrong: 'istirahət etmək'},
  { en: 'to teach',    tr: 'öyrətmək',           wrong: 'öyrənmək'       },
  { en: 'to write',    tr: 'yazmaq',             wrong: 'oxumaq'         },
  { en: 'to spell',    tr: 'hərfləmək',          wrong: 'tələffüz etmək' },
  { en: 'to repeat',   tr: 'təkrarlamaq',        wrong: 'davam etmək'    },
],

// ─────────────────────── QUIZ 32 — İdman / Sport & Hobbies ───────────────────────
[
  { en: 'art',         tr: 'sənət',              wrong: 'musiqi'         },
  { en: 'ball',        tr: 'top',                wrong: 'raket'          },
  { en: 'chess',       tr: 'şahmat',             wrong: 'dama'           },
  { en: 'concert',     tr: 'konsert',            wrong: 'şou'            },
  { en: 'cooking',     tr: 'bişirmə',            wrong: 'rəsm çəkmə'     },
  { en: 'dancing',     tr: 'rəqs etmə',          wrong: 'oxuma'          },
  { en: 'festival',    tr: 'festival',           wrong: 'konsert'        },
  { en: 'football',    tr: 'futbol',             wrong: 'basketbol'      },
  { en: 'game',        tr: 'oyun',               wrong: 'matç'           },
  { en: 'guitar',      tr: 'gitara',             wrong: 'piano'          },
  { en: 'hobby',       tr: 'hobbi',              wrong: 'peşə'           },
  { en: 'match',       tr: 'matç / oyun',        wrong: 'turnir'         },
  { en: 'painting',    tr: 'rəsm çəkmə / tablo', wrong: 'heykəltəraşlıq' },
  { en: 'piano',       tr: 'piano',              wrong: 'gitara'         },
  { en: 'pool',        tr: 'hovuz',              wrong: 'idman zalı'     },
  { en: 'singing',     tr: 'oxuma / mahnı oxuma', wrong: 'rəqs etmə'    },
  { en: 'sport',       tr: 'idman',              wrong: 'hobbi'          },
  { en: 'swimming',    tr: 'üzmə',               wrong: 'qaçış'          },
  { en: 'team',        tr: 'komanda',            wrong: 'oyunçu'         },
  { en: 'tennis',      tr: 'tennis',             wrong: 'badminton'      },
],
      { type: 'exam', name: 'Exam 9 — Məktəb & İdman', sourceQuizzes: [31,32,33] },

// ─────────────────────── QUIZ 33 — Feil 1 / Movement verbs ───────────────────────
[
  { en: 'to arrive',   tr: 'çatmaq / gəlmək',   wrong: 'getmək'         },
  { en: 'to bring',    tr: 'gətirmək',           wrong: 'aparmaq'        },
  { en: 'to carry',    tr: 'daşımaq / aparmaq',  wrong: 'qoymaq'         },
  { en: 'to climb',    tr: 'dırmaşmaq',          wrong: 'düşmək'         },
  { en: 'to come',     tr: 'gəlmək',             wrong: 'getmək'         },
  { en: 'to fall',     tr: 'düşmək / yıxılmaq',  wrong: 'qalxmaq'        },
  { en: 'to fly',      tr: 'uçmaq',              wrong: 'üzmək'          },
  { en: 'to follow',   tr: 'izləmək / ardınca getmək', wrong: 'qaçmaq'  },
  { en: 'to go',       tr: 'getmək',             wrong: 'gəlmək'         },
  { en: 'to leave',    tr: 'ayrılmaq / getmək',  wrong: 'qalmaq'         },
  { en: 'to move',     tr: 'hərəkət etmək',      wrong: 'dayanmaq'       },
  { en: 'to ride',     tr: 'minmək / sürmək',    wrong: 'yüyürmək'       },
  { en: 'to run',      tr: 'qaçmaq',             wrong: 'gəzmək'         },
  { en: 'to sit',      tr: 'oturmaq',            wrong: 'durmaq'         },
  { en: 'to stand',    tr: 'durmaq / ayağa qalxmaq', wrong: 'oturmaq'   },
  { en: 'to turn',     tr: 'dönmək / çevirmək',  wrong: 'getmək'         },
  { en: 'to walk',     tr: 'gəzmək / yeriməmk',  wrong: 'qaçmaq'         },
  { en: 'to wake',     tr: 'oyanmaq',            wrong: 'yatmaq'         },
  { en: 'to jump',     tr: 'atlamaq / tullanmaq', wrong: 'qaçmaq'        },
  { en: 'to return',   tr: 'qayıtmaq',           wrong: 'getmək'         },
],

// ─────────────────────── QUIZ 34 — Feil 2 / Communication verbs ───────────────────────
[
  { en: 'to answer',   tr: 'cavablamaq',         wrong: 'sual vermək'    },
  { en: 'to ask',      tr: 'soruşmaq',           wrong: 'cavablamaq'     },
  { en: 'to call',     tr: 'zəng etmək / çağırmaq', wrong: 'göndərmək'  },
  { en: 'to explain',  tr: 'izah etmək',         wrong: 'sual vermək'    },
  { en: 'to guess',    tr: 'təxmin etmək',       wrong: 'bilmək'         },
  { en: 'to introduce', tr: 'təqdim etmək',      wrong: 'izah etmək'     },
  { en: 'to laugh',    tr: 'gülmək',             wrong: 'ağlamaq'        },
  { en: 'to listen',   tr: 'qulaq asmaq',        wrong: 'danışmaq'       },
  { en: 'to read',     tr: 'oxumaq',             wrong: 'yazmaq'         },
  { en: 'to repeat',   tr: 'təkrarlamaq',        wrong: 'davam etmək'    },
  { en: 'to say',      tr: 'demək',              wrong: 'soruşmaq'       },
  { en: 'to send',     tr: 'göndərmək',          wrong: 'almaq'          },
  { en: 'to show',     tr: 'göstərmək',          wrong: 'gizlətmək'      },
  { en: 'to sing',     tr: 'mahnı oxumaq',       wrong: 'rəqs etmək'     },
  { en: 'to speak',    tr: 'danışmaq',           wrong: 'susmaaq'        },
  { en: 'to spell',    tr: 'hərfləmək',          wrong: 'tələffüz etmək' },
  { en: 'to talk',     tr: 'söhbət etmək',       wrong: 'susmaaq'        },
  { en: 'to tell',     tr: 'söyləmək / danışmaq', wrong: 'soruşmaq'      },
  { en: 'to thank',    tr: 'təşəkkür etmək',     wrong: 'üzr istəmək'    },
  { en: 'to write',    tr: 'yazmaq',             wrong: 'oxumaq'         },
],
// ─────────────────────── QUIZ 35 — Feil 3 / Daily life verbs ───────────────────────
[
  { en: 'to add',       tr: 'əlavə etmək',        wrong: 'çıxarmaq'       },
  { en: 'to buy',       tr: 'almaq',              wrong: 'satmaq'         },
  { en: 'to change',    tr: 'dəyişmək',           wrong: 'saxlamaq'       },
  { en: 'to check',     tr: 'yoxlamaq',           wrong: 'düzəltmək'      },
  { en: 'to clean',     tr: 'təmizləmək',         wrong: 'çirkləndirmək'  },
  { en: 'to close',     tr: 'bağlamaq',           wrong: 'açmaq'          },
  { en: 'to cook',      tr: 'bişirmək',           wrong: 'yemək'          },
  { en: 'to cut',       tr: 'kəsmək',             wrong: 'yapışdırmaq'    },
  { en: 'to dance',     tr: 'rəqs etmək',         wrong: 'oxumaq'         },
  { en: 'to drink',     tr: 'içmək',              wrong: 'yemək'          },
  { en: 'to eat',       tr: 'yemək',              wrong: 'içmək'          },
  { en: 'to fill',      tr: 'doldurmaq',          wrong: 'boşaltmaq'      },
  { en: 'to finish',    tr: 'bitirmək',           wrong: 'başlamaq'       },
  { en: 'to fix',       tr: 'düzəltmək',          wrong: 'sındırmaq'      },
  { en: 'to get',       tr: 'almaq / əldə etmək', wrong: 'vermək'         },
  { en: 'to give',      tr: 'vermək',             wrong: 'almaq'          },
  { en: 'to grow',      tr: 'böyümək / yetişdirmək', wrong: 'azalmaq'     },
  { en: 'to have',      tr: 'sahib olmaq / var olmaq', wrong: 'istəmək'   },
  { en: 'to help',      tr: 'kömək etmək',        wrong: 'mane olmaq'     },
  { en: 'to keep',      tr: 'saxlamaq',           wrong: 'atmaq'          },
],
      { type: 'exam', name: 'Exam 10 — Feillər 1', sourceQuizzes: [34,35,36] },
      
// ─────────────────────── QUIZ 36 — Feil 4 / Daily life verbs 2 ───────────────────────
[
  { en: 'to live',      tr: 'yaşamaq',            wrong: 'ölmək'          },
  { en: 'to look',      tr: 'baxmaq',             wrong: 'görmək'         },
  { en: 'to make',      tr: 'etmək / düzəltmək',  wrong: 'dağıtmaq'       },
  { en: 'to meet',      tr: 'görüşmək / tanışmaq', wrong: 'ayrılmaq'      },
  { en: 'to miss',      tr: 'darıxmaq / qaçırmaq', wrong: 'çatmaq'        },
  { en: 'to open',      tr: 'açmaq',              wrong: 'bağlamaq'       },
  { en: 'to order',     tr: 'sifariş etmək',      wrong: 'ödəmək'         },
  { en: 'to own',       tr: 'sahib olmaq',        wrong: 'itirmək'        },
  { en: 'to paint',     tr: 'rəsm çəkmək / boyamaq', wrong: 'silmək'      },
  { en: 'to pay',       tr: 'ödəmək',             wrong: 'almaq'          },
  { en: 'to play',      tr: 'oynamaq',            wrong: 'işləmək'        },
  { en: 'to put',       tr: 'qoymaq',             wrong: 'götürmək'       },
  { en: 'to relax',     tr: 'istirahət etmək',    wrong: 'işləmək'        },
  { en: 'to sleep',     tr: 'yatmaq',             wrong: 'oyanmaq'        },
  { en: 'to spend',     tr: 'xərcləmək / keçirmək', wrong: 'qazanmaq'     },
  { en: 'to start',     tr: 'başlamaq',           wrong: 'bitirmək'       },
  { en: 'to stop',      tr: 'dayanmaq / dayandırmaq', wrong: 'davam etmək'},
  { en: 'to swim',      tr: 'üzmək',              wrong: 'qaçmaq'         },
  { en: 'to take',      tr: 'götürmək / almaq',   wrong: 'vermək'         },
  { en: 'to try',       tr: 'cəhd etmək',         wrong: 'imtina etmək'   },
],

// ─────────────────────── QUIZ 37 — Feil 5 / Mental & abstract verbs ───────────────────────
[
  { en: 'to become',    tr: 'olmaq / çevrilmək',  wrong: 'qalmaq'         },
  { en: 'to begin',     tr: 'başlamaq',           wrong: 'bitirmək'       },
  { en: 'to believe',   tr: 'inanmaq',            wrong: 'şübhə etmək'    },
  { en: 'to build',     tr: 'inşa etmək / qurmaq', wrong: 'dağıtmaq'      },
  { en: 'to complete',  tr: 'tamamlamaq',         wrong: 'başlamaq'       },
  { en: 'to decide',    tr: 'qərar vermək',       wrong: 'şübhə etmək'    },
  { en: 'to do',        tr: 'etmək / yapmaq',     wrong: 'dayandırmaq'    },
  { en: 'to enjoy',     tr: 'zövq almaq',         wrong: 'nifrət etmək'   },
  { en: 'to feel',      tr: 'hiss etmək',         wrong: 'düşünmək'       },
  { en: 'to find',      tr: 'tapmaq',             wrong: 'itirmək'        },
  { en: 'to forget',    tr: 'unutmaq',            wrong: 'xatırlamaq'     },
  { en: 'to hate',      tr: 'nifrət etmək',       wrong: 'sevmək'         },
  { en: 'to hear',      tr: 'eşitmək',            wrong: 'görmək'         },
  { en: 'to hope',      tr: 'ümid etmək',         wrong: 'ümidsiz olmaq'  },
  { en: 'to include',   tr: 'daxil etmək',        wrong: 'xaric etmək'    },
  { en: 'to join',      tr: 'qoşulmaq / birləşmək', wrong: 'ayrılmaq'     },
  { en: 'to know',      tr: 'bilmək',             wrong: 'unutmaq'        },
  { en: 'to lose',      tr: 'itirmək / udmaq',    wrong: 'tapmaq'         },
  { en: 'to love',      tr: 'sevmək',             wrong: 'nifrət etmək'   },
  { en: 'to mean',      tr: 'mənası olmaq / demək istəmək', wrong: 'bilmək'},
],

// ─────────────────────── QUIZ 38 — Feil 6 / Mental verbs 2 ───────────────────────
[
  { en: 'to need',      tr: 'ehtiyac duymaq',     wrong: 'istəmək'        },
  { en: 'to plan',      tr: 'planlaşdırmaq',      wrong: 'ləğv etmək'     },
  { en: 'to practise',  tr: 'məşq etmək',         wrong: 'dinlənmək'      },
  { en: 'to remember',  tr: 'xatırlamaq',         wrong: 'unutmaq'        },
  { en: 'to see',       tr: 'görmək',             wrong: 'eşitmək'        },
  { en: 'to think',     tr: 'düşünmək',           wrong: 'hiss etmək'     },
  { en: 'to understand',tr: 'başa düşmək',        wrong: 'anlamaq'        },
  { en: 'to use',       tr: 'istifadə etmək',     wrong: 'atmaq'          },
  { en: 'to wait',      tr: 'gözləmək',           wrong: 'getmək'         },
  { en: 'to want',      tr: 'istəmək',            wrong: 'ehtiyac duymaq' },
  { en: 'to wash',      tr: 'yumaq',              wrong: 'çirkləndirmək'  },
  { en: 'to watch',     tr: 'izləmək / seyr etmək', wrong: 'dinləmək'     },
  { en: 'to win',       tr: 'qazanmaq / udmaq',   wrong: 'uduzmaaq'       },
  { en: 'to work',      tr: 'işləmək',            wrong: 'istirahət etmək'},
  { en: 'to draw',      tr: 'rəsm çəkmək',        wrong: 'boyamaq'        },
  { en: 'to die',       tr: 'ölmək',              wrong: 'yaşamaq'        },
  { en: 'to let',       tr: 'icazə vermək',       wrong: 'qadağan etmək'  },
  { en: 'to lie',       tr: 'uzanmaq / yalan söyləmək', wrong: 'oturmaq'  },
  { en: 'to break',     tr: 'sındırmaq',          wrong: 'düzəltmək'      },
  { en: 'to wear',      tr: 'geymək',             wrong: 'çıxarmaq'       },
],
      { type: 'exam', name: 'Exam 11 — Feillər 2', sourceQuizzes: [37,38,39] },

// ─────────────────────── QUIZ 39 — İş / Work & Business ───────────────────────
[
  { en: 'action',       tr: 'hərəkət / fəaliyyət', wrong: 'fikir'         },
  { en: 'activity',     tr: 'fəaliyyət',          wrong: 'istirahət'      },
  { en: 'business',     tr: 'biznes / iş',        wrong: 'hobbi'          },
  { en: 'company',      tr: 'şirkət',             wrong: 'komanda'        },
  { en: 'interview',    tr: 'müsahibə',           wrong: 'imtahan'        },
  { en: 'job',          tr: 'iş / vəzifə',        wrong: 'hobbi'          },
  { en: 'meeting',      tr: 'görüş / iclас',      wrong: 'müsahibə'       },
  { en: 'model',        tr: 'model',              wrong: 'nümunə'         },
  { en: 'office',       tr: 'ofis',               wrong: 'fabrik'         },
  { en: 'plan',         tr: 'plan',               wrong: 'hesabat'        },
  { en: 'problem',      tr: 'problem',            wrong: 'həll'           },
  { en: 'project',      tr: 'layihə',             wrong: 'plan'           },
  { en: 'reason',       tr: 'səbəb',              wrong: 'nəticə'         },
  { en: 'report',       tr: 'hesabat',            wrong: 'plan'           },
  { en: 'rule',         tr: 'qayda',              wrong: 'istisna'        },
  { en: 'work',         tr: 'iş',                 wrong: 'istirahət'      },
  { en: 'to work',      tr: 'işləmək',            wrong: 'istirahət etmək'},
  { en: 'to complete',  tr: 'tamamlamaq',         wrong: 'başlamaq'       },
  { en: 'to plan',      tr: 'planlaşdırmaq',      wrong: 'ləğv etmək'     },
  { en: 'to fix',       tr: 'düzəltmək',          wrong: 'sındırmaq'      },
],

// ─────────────────────── QUIZ 40 — Müxtəlif İsimlər / Misc nouns ───────────────────────
[
  { en: 'beginning',    tr: 'başlanğıc',          wrong: 'son'            },
  { en: 'chart',        tr: 'cədvəl / qrafik',    wrong: 'xəritə'         },
  { en: 'end',          tr: 'son',                wrong: 'başlanğıc'      },
  { en: 'form',         tr: 'forma / bianket',    wrong: 'sənəd'          },
  { en: 'fun',          tr: 'əyləncə / zövq',     wrong: 'sıkıntı'        },
  { en: 'group',        tr: 'qrup',               wrong: 'fərd'           },
  { en: 'idea',         tr: 'fikir / ideya',      wrong: 'plan'           },
  { en: 'information',  tr: 'məlumat',            wrong: 'sual'           },
  { en: 'interest',     tr: 'maraq / faiz',       wrong: 'biganəlik'      },
  { en: 'kind',         tr: 'növ / cür',          wrong: 'rəng'           },
  { en: 'life',         tr: 'həyat',              wrong: 'ölüm'           },
  { en: 'line',         tr: 'xətt / sıra',        wrong: 'nöqtə'          },
  { en: 'list',         tr: 'siyahı',             wrong: 'cədvəl'         },
  { en: 'lot',          tr: 'çox / xeyli',        wrong: 'az'             },
  { en: 'map',          tr: 'xəritə',             wrong: 'plan'           },
  { en: 'meaning',      tr: 'məna',               wrong: 'söz'            },
  { en: 'mistake',      tr: 'səhv',               wrong: 'cavab'          },
  { en: 'part',         tr: 'hissə',              wrong: 'tam'            },
  { en: 'point',        tr: 'nöqtə / məqam',      wrong: 'xətt'           },
  { en: 'sound',        tr: 'səs',                wrong: 'şəkil'          },
],

// ─────────────────────── QUIZ 41 — Müxtəlif İsimlər 2 / Misc nouns 2 ───────────────────────
[
  { en: 'space',        tr: 'məkan / kosmoz',     wrong: 'yer'            },
  { en: 'style',        tr: 'üslub / stil',       wrong: 'moda'           },
  { en: 'type',         tr: 'növ / tip',          wrong: 'forma'          },
  { en: 'way',          tr: 'yol / üsul',         wrong: 'məkan'          },
  { en: 'cup',          tr: 'fincan',             wrong: 'stəkan'         },
  { en: 'glass',        tr: 'stəkan / şüşə',      wrong: 'fincan'         },
  { en: 'bottle',       tr: 'şüşə / butulka',     wrong: 'qutu'           },
  { en: 'box',          tr: 'qutu',               wrong: 'çanta'          },
  { en: 'piece',        tr: 'parça / hissə',      wrong: 'tam'            },
  { en: 'thing',        tr: 'şey',                wrong: 'yer'            },
  { en: 'stuff',        tr: 'şeylər / əşyalar',   wrong: 'məlumat'        },
  { en: 'item',         tr: 'maddə / əşya',       wrong: 'siyahı'         },
  { en: 'model',        tr: 'model',              wrong: 'tip'            },
  { en: 'size',         tr: 'ölçü / beden',       wrong: 'forma'          },
  { en: 'shape',        tr: 'forma / şəkil',      wrong: 'rəng'           },
  { en: 'colour',       tr: 'rəng',               wrong: 'forma'          },
  { en: 'name',         tr: 'ad / isim',          wrong: 'soyad'          },
  { en: 'title',        tr: 'başlıq / ünvan',     wrong: 'ad'             },
  { en: 'number',       tr: 'rəqəm / nömrə',      wrong: 'hərf'           },
],
      { type: 'exam', name: 'Exam 12 — İş & İsimlər', sourceQuizzes: [40,41,42] },


      // ─────────────────────── QUIZ 10 ──────────────────────
      [
        // { en: 'söz', tr: 'düzgün tərcümə', wrong: 'yanlış tərcümə' },
      ],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 2 — A2: Əsas Səviyyə                     ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'a2',
    name: 'A2 — Əsas Səviyyə',
    icon: '🌿',
    color: '#9B6FD4',
    quizzes: [
      // QUIZ 1 — A2
      [ /* { en: '...', tr: '...', wrong: '...' }, */ ],
      // QUIZ 2
      [],
      // QUIZ 3
      [],
      // QUIZ 4
      [],
      // QUIZ 5
      [],
      // QUIZ 6
      [],
      // QUIZ 7
      [],
      // QUIZ 8
      [],
      // QUIZ 9
      [],
      // QUIZ 10
      [],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 3 — B1: Orta-Aşağı I                     ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'b1a',
    name: 'B1 — Orta-Aşağı I',
    icon: '🌳',
    color: '#E07A30',
    quizzes: [
      [], [], [], [], [],
      [], [], [], [], [],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 4 — B1+: Orta-Aşağı II                   ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'b1b',
    name: 'B1+ — Orta-Aşağı II',
    icon: '🌲',
    color: '#E8A020',
    quizzes: [
      [], [], [], [], [],
      [], [], [], [], [],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 5 — B2: Orta Səviyyə I                   ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'b2a',
    name: 'B2 — Orta Səviyyə I',
    icon: '⚡',
    color: '#2EAA6E',
    quizzes: [
      [], [], [], [], [],
      [], [], [], [], [],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 6 — B2+: Orta Səviyyə II                 ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'b2b',
    name: 'B2+ — Orta Səviyyə II',
    icon: '🔥',
    color: '#D44E30',
    quizzes: [
      [], [], [], [], [],
      [], [], [], [], [],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 7 — C1: İrəliləmiş I                     ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'c1a',
    name: 'C1 — İrəliləmiş I',
    icon: '💎',
    color: '#3BAAB5',
    quizzes: [
      [], [], [], [], [],
      [], [], [], [], [],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 8 — C1+: İrəliləmiş II                   ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'c1b',
    name: 'C1+ — İrəliləmiş II',
    icon: '🏆',
    color: '#7058D0',
    quizzes: [
      [], [], [], [], [],
      [], [], [], [], [],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 9 — C2: Ustalıq Səviyyəsi                ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'c2',
    name: 'C2 — Ustalıq',
    icon: '👑',
    color: '#2C3E50',
    quizzes: [
      [], [], [], [], [],
      [], [], [], [], [],
    ]
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  LEVEL 10 — İş Ingilis dili                     ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: 'business',
    name: 'Business English',
    icon: '💼',
    color: '#8B7355',
    quizzes: [
      [], [], [], [], [],
      [], [], [], [], [],
    ]
  },
];
